services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: false
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_CONNECTION_URL
        value: postgresql://n8n_db_wonb_user:Qj5MAbEfw8YEOngRQOGULK1bc5xJWcki@dpg-d0kfsl3uibrs739grl50-a.oregon-postgres.render.com/n8n_db_wonb
