services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: false
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_URL
        value: ${DB_POSTGRESDB_CONNECTION_URL}
